###
set: "default"
models:
  any:
    model: "gpt-5-mini"
    provider: "openai"
    base_url: "https://api.openai.com/v1/"
    api_key: "openai"
  anthropic:
    model: "claude-3-5-haiku-latest"
    provider: "anthropic"
    base_url: "https://api.anthropic.com/"
    api_key: "anthropic"
  gemini:
    model: "gemini-2.5-flash-lite"
    provider: "gemini"
    base_url: "https://generativelanguage.googleapis.com/v1beta/"
    api_key: "gemini"
  openai:
    model: "gpt-5-nano"
    provider: "openai"
    base_url: "https://api.openai.com/v1/"
    api_key: "openai"
  xai:
    model: "grok-4-1-fast-non-reasoning"
    provider: "xai"
    base_url: "https://api.x.ai/v1/"
    api_key: "xai"
